
//This file should be called cbmc_main_ab5.c
//This is autogenerated code. Edit by hand at your peril!

//It can be used with the cbmc model checker
//Call it using the following command: 
//$ cbmc cbmc_main_ab5.c F_ab5.c


#include "F_ab5.h"
#include <stdio.h>
#include <stdint.h>

int main() {


	//I/O and state for ab5
	enforcervars_ab5_t enf_ab5;
    inputs_ab5_t inputs_ab5;
    outputs_ab5_t outputs_ab5;

	//set values to known state
    ab5_init_all_vars(&enf_ab5, &inputs_ab5, &outputs_ab5);

	//introduce nondeterminism
    //a nondet_xxxxx function name tells cbmc that it could be anything, but must be unique
    //randomise inputs
	inputs_ab5.A = nondet_ab5_input_0();
	

	//randomise enforcer state, i.e. clock values and position (excepting violation state)
	enf_ab5.v = nondet_ab5_enf_AB5_0();
	
	enf_ab5._policy_AB5_state = nondet_ab5_enf_AB5_state() % 2;
	

    //run the enforcer (i.e. tell CBMC to check this out)
	ab5_run_via_enforcer(&enf_ab5, &inputs_ab5, &outputs_ab5);

}


void ab5_run(inputs_ab5_t *inputs, outputs_ab5_t *outputs) {
    //randomise controller

    outputs->B = nondet_ab5_output_0();
	 
}

